package io.github.some_example_name.screens;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.Screen;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.scenes.scene2d.InputEvent;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.ui.Image;
import com.badlogic.gdx.scenes.scene2d.ui.Dialog;
import com.badlogic.gdx.scenes.scene2d.ui.Label;
import com.badlogic.gdx.scenes.scene2d.ui.ScrollPane;
import com.badlogic.gdx.scenes.scene2d.ui.Stack;
import com.badlogic.gdx.scenes.scene2d.ui.Table;
import com.badlogic.gdx.scenes.scene2d.ui.TextButton;
import com.badlogic.gdx.scenes.scene2d.utils.ClickListener;
import com.badlogic.gdx.utils.Align;
import io.github.some_example_name.Main;
import io.github.some_example_name.model.*;
import io.github.some_example_name.utils.*;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/** Evento de seleção do Draft: ordem, prospects e relatório de scouting na mesma tela. */
public class DraftScreen implements Screen {
    private final Main game; private final Club club; private final DraftScoutManager scout; private final Stage stage;
    private List<DraftPick> picks; private Player selected; private String filter="TODOS"; private boolean pauseAfterUserPick;
    public DraftScreen(Main game,Club club,DraftScoutManager scout){this.game=game;this.club=club;this.scout=scout;stage=new Stage(new ResponsiveViewport());}
    @Override public void show(){Gdx.input.setInputProcessor(stage);refresh();}
    private void refresh(){if(game.league.isDraftFinalized()){game.setScreen(new DraftSummaryScreen(game,club));return;}if(!pauseAfterUserPick)advanceAiPicks(Integer.MAX_VALUE);picks=DraftOrderService.getCurrentDraftOrder(game.league,game.league.getCurrentSeason()+1);List<Player> available=available();if(selected==null||!available.contains(selected))selected=available.isEmpty()?null:available.get(0);DraftPick current=currentPick();if(current==null){for(Player player:available)player.transferTo(null);game.freeAgencyService.addUndraftedFreeAgents(available);game.league.finalizeDraft();game.setScreen(new DraftSummaryScreen(game,club));return;}stage.clear();Stack root=new Stack();root.setFillParent(true);stage.addActor(root);root.add(new Image(game.background));Table page=ScreenUI.createPage(true);String sub=current.getRound()+"ª RODADA • PICK #"+overall(current);page.add(ScreenUI.createHeader(game.skin,"WFL DRAFT • "+(game.league.getCurrentSeason()+1),sub)).growX().height(ScreenUI.HEADER_HEIGHT).padBottom(10).row();Table columns=new Table();columns.add(orderPanel()).width(330).growY().padRight(8);columns.add(prospectPanel(available)).grow().padRight(8);columns.add(reportPanel(current)).width(315).growY();page.add(columns).grow().row();page.add(bottomPanel(current)).growX().height(76).padTop(9);root.add(page);}
    private Table orderPanel(){Table panel=ScreenUI.createPanel();panel.top();panel.add(ScreenUI.createSectionTitle(game.skin,"ORDEM DO DRAFT")).left().padBottom(7).row();Table rows=new Table();rows.top();for(DraftPick p:picks){int number=overall(p);DraftSelection selection=selection(p);boolean current=p==currentPick();String title="#"+number+"  "+p.getCurrentOwner().getName();if(p.getOriginalOwner()!=p.getCurrentOwner())title+="\nvia "+p.getOriginalOwner().getName();if(selection!=null)title+="   ✓ "+selection.getPlayer().getName();else if(current&&p.getCurrentOwner()==club)title+="   ▶ SUA VEZ";Label row=ScreenUI.createSubtitle(game.skin,title);row.setColor(current?StyleFactory.SOFT_YELLOW:selection!=null?ScreenUI.SUCCESS:StyleFactory.CREME_AGED);row.setWrap(true);rows.add(row).growX().left().pad(4,5,4,5).row();}ScrollPane scroll=new ScrollPane(rows,game.skin);scroll.setFadeScrollBars(false);panel.add(scroll).grow();return panel;}
    private Table prospectPanel(List<Player> available){Table panel=ScreenUI.createPanel();panel.top();panel.add(ScreenUI.createSectionTitle(game.skin,"PROSPECTOS DISPONÍVEIS")).colspan(6).left().padBottom(6).row();header(panel,"NOME","POS","ID","OVR","POT","SCOUT");Table list=new Table();list.top();for(Player p:available)if(matches(p)){ScoutTarget t=target(p);boolean active=p==selected;TextButton b=ScreenUI.createInteractiveButton(p.getName(),game.skin);b.getLabel().setFontScale(.5f);b.addListener(new ClickListener(){@Override public void clicked(InputEvent e,float x,float y){selected=p;refresh();}});list.add(b).width(155).height(32);list.add(cell(p.getPrimaryPosition().name(),active)).width(45);list.add(cell(String.valueOf(p.getAge()),active)).width(38);list.add(cell(displayOvr(p,t),active)).width(55);list.add(cell(displayPot(p,t),active)).width(55);list.add(cell(t==null?"0%":Math.round(t.getKnowledgePercentage())+"%",active)).width(55).row();}ScrollPane scroll=new ScrollPane(list,game.skin);scroll.setFadeScrollBars(false);panel.add(scroll).colspan(6).grow().row();Table filters=new Table();for(String f:new String[]{"TODOS","GK","DEF","MEI","ATA","★"}){TextButton b=ScreenUI.createInteractiveButton(f,game.skin);b.getLabel().setFontScale(.45f);b.addListener(new ClickListener(){@Override public void clicked(InputEvent e,float x,float y){filter=f;refresh();}});filters.add(b).width(65).height(30).pad(2);}panel.add(filters).colspan(6).center().padTop(5);return panel;}
    private Table reportPanel(DraftPick current){Table panel=ScreenUI.createPanel();panel.top();panel.add(ScreenUI.createSectionTitle(game.skin,"PROSPECTO")).center().padBottom(12).row();if(selected==null){panel.add(ScreenUI.createSubtitle(game.skin,"Draft concluído.")).center();return panel;}ScoutTarget t=target(selected);panel.add(ScreenUI.createBoldValue(game.skin,selected.getName().toUpperCase(),StyleFactory.SOFT_YELLOW,Align.center)).center().row();panel.add(ScreenUI.createSubtitle(game.skin,selected.getNationality()+" • "+selected.getPrimaryPosition()+" • "+selected.getAge()+" anos")).center().padTop(5).row();panel.add(ScreenUI.createSubtitle(game.skin,"Conhecimento: "+(t==null?0:Math.round(t.getKnowledgePercentage()))+"%")).center().padTop(12).row();stat(panel,"OVR",displayOvr(selected,t));stat(panel,"POTENCIAL",displayPot(selected,t));stat(panel,"ATA",attribute(selected,"ataque",t));stat(panel,"PAS",attribute(selected,"passe",t));stat(panel,"DEF",attribute(selected,"defesa",t));stat(panel,"FIS",attribute(selected,"fisico",t));stat(panel,"DRI",attribute(selected,"drible",t));panel.add(ScreenUI.createSubtitle(game.skin,"Projeção: "+projection(selected))).center().padTop(12).row();Player tip=recommended();panel.add(ScreenUI.createSectionTitle(game.skin,"RECOMENDAÇÃO DO SCOUT")).center().padTop(13).row();panel.add(ScreenUI.createBoldValue(game.skin,tip.getName()+" • "+stars(recommendationStars(tip)),StyleFactory.SOFT_YELLOW,Align.center)).center().padTop(4).row();Label rationale=ScreenUI.createSubtitle(game.skin,recommendationText(tip));rationale.setWrap(true);rationale.setAlignment(Align.center);panel.add(rationale).width(270).center().padTop(4).row();TextButton favorite=ScreenUI.createInteractiveButton(scout.isFavorite(selected)?"★ FAVORITO":"☆ FAVORITAR",game.skin);favorite.getLabel().setFontScale(.5f);favorite.addListener(new ClickListener(){@Override public void clicked(InputEvent e,float x,float y){scout.toggleFavorite(selected);refresh();}});panel.add(favorite).width(180).height(38).center().padTop(10);return panel;}
    private Table bottomPanel(DraftPick current){Table panel=ScreenUI.createPanel();boolean yours=current!=null&&current.getCurrentOwner()==club;String clock=yours?club.getName().toUpperCase()+" ESTÁ NO RELÓGIO • 02:00":"ACOMPANHE AS PRÓXIMAS ESCOLHAS";panel.add(ScreenUI.createSectionTitle(game.skin,clock)).left().expandX();Label need=ScreenUI.createSubtitle(game.skin,"NECESSIDADES  "+needs());need.setWrap(true);panel.add(need).width(390).left().padRight(8);if(yours){TextButton trade=ScreenUI.createInteractiveButton("NEGOCIAR PICK",game.skin);trade.getLabel().setFontScale(.45f);trade.addListener(new ClickListener(){@Override public void clicked(InputEvent e,float x,float y){game.setScreen(new TradeHubScreen(game,club));}});panel.add(trade).width(135).height(42).padRight(5);TextButton draft=ScreenUI.createPrimaryButton(game.skin,"DRAFTAR "+(selected==null?"":selected.getName()));draft.setDisabled(selected==null);draft.addListener(new ClickListener(){@Override public void clicked(InputEvent e,float x,float y){confirmDraft(current);}});panel.add(draft).width(195).height(46);}else if(pauseAfterUserPick){TextButton next=ScreenUI.createInteractiveButton("PRÓXIMA PICK",game.skin);next.getLabel().setFontScale(.43f);next.addListener(new ClickListener(){@Override public void clicked(InputEvent e,float x,float y){advanceAiPicks(1);refresh();}});panel.add(next).width(120).height(42).padRight(4);TextButton sim=ScreenUI.createPrimaryButton(game.skin,"ATÉ MINHA PICK");sim.getLabel().setFontScale(.43f);sim.addListener(new ClickListener(){@Override public void clicked(InputEvent e,float x,float y){pauseAfterUserPick=false;refresh();}});panel.add(sim).width(140).height(42).padRight(4);TextButton round=ScreenUI.createInteractiveButton("SIMULAR RODADA",game.skin);round.getLabel().setFontScale(.4f);round.addListener(new ClickListener(){@Override public void clicked(InputEvent e,float x,float y){simulateRound();refresh();}});panel.add(round).width(140).height(42);}return panel;}
    private void advanceAiPicks(int max){List<DraftPick> order=DraftOrderService.getCurrentDraftOrder(game.league,game.league.getCurrentSeason()+1);int made=0;for(DraftPick p:order){if(game.league.isDraftPickUsed(p))continue;if(p.getCurrentOwner()==club||made>=max)break;List<Player> pool=available();if(pool.isEmpty())break;pool.sort(Comparator.comparingInt((Player x)->draftScore(p.getCurrentOwner(),x)).reversed());game.league.recordDraftSelection(p,pool.get(0));made++;}}
    private void simulateRound(){DraftPick current=currentPick();if(current==null)return;int round=current.getRound();List<DraftPick> order=DraftOrderService.getCurrentDraftOrder(game.league,game.league.getCurrentSeason()+1);for(DraftPick p:order){if(p.getRound()!=round||game.league.isDraftPickUsed(p))continue;if(p.getCurrentOwner()==club)break;List<Player> pool=available();if(pool.isEmpty())return;pool.sort(Comparator.comparingInt((Player x)->draftScore(p.getCurrentOwner(),x)).reversed());game.league.recordDraftSelection(p,pool.get(0));}}
    private List<Player> available(){List<Player> list=new ArrayList<>();for(Player p:game.draftClass){boolean taken=false;for(DraftSelection s:game.league.getDraftSelections())if(s.getPlayer()==p){taken=true;break;}if(!taken)list.add(p);}list.sort(Comparator.comparingInt((Player p)->p.getOverall()+p.getPotential()/3).reversed());return list;}
    private DraftPick currentPick(){if(picks==null)picks=DraftOrderService.getCurrentDraftOrder(game.league,game.league.getCurrentSeason()+1);for(DraftPick p:picks)if(!game.league.isDraftPickUsed(p))return p;return null;}
    private DraftSelection selection(DraftPick p){for(DraftSelection s:game.league.getDraftSelections())if(s.getPick()==p)return s;return null;}
    private int overall(DraftPick p){return (p.getRound()-1)*20+p.getProjectedPosition();}
    private ScoutTarget target(Player p){if(scout==null)return null;for(ScoutTarget t:scout.getActiveTargets())if(t.getPlayer()==p)return t;for(ScoutTarget t:scout.getCompletedTargets())if(t.getPlayer()==p)return t;return null;}
    private String displayOvr(Player p,ScoutTarget t){return t==null?"?":t.getDisplayOverall();} private String displayPot(Player p,ScoutTarget t){return t==null?"?":t.getDisplayPotential();} private String attribute(Player p,String key,ScoutTarget t){return t==null?"?":t.getAttributeDisplay(p.getTechnicalAttributes().getAttributeByName(key));}
    private boolean matches(Player p){if("TODOS".equals(filter))return true;if("★".equals(filter))return scout.isFavorite(p);String pos=p.getPrimaryPosition().name();if("GK".equals(filter))return "GK".equals(pos);if("DEF".equals(filter))return pos.endsWith("B");if("MEI".equals(filter))return pos.contains("M");return pos.equals("ST")||pos.equals("CF")||pos.equals("LW")||pos.equals("RW");}
    private Label cell(String text,boolean selectedRow){return ScreenUI.createBoldValue(game.skin,text,selectedRow?StyleFactory.SOFT_YELLOW:StyleFactory.CREME_AGED,Align.center);} private void header(Table p,String... a){for(String s:a)p.add(ScreenUI.createTableHeaderLabel(game.skin,s,Align.center));p.row();}private void stat(Table p,String n,String v){p.add(ScreenUI.createSubtitle(game.skin,n)).left().expandX().padTop(7);p.add(ScreenUI.createBoldValue(game.skin,v,StyleFactory.SOFT_YELLOW,Align.right)).right().padTop(7).row();}
    private void confirmDraft(final DraftPick pick){if(pick==null||selected==null)return;final Player choice=selected;Dialog dialog=new Dialog("CONFIRMAR ESCOLHA",game.skin);dialog.text("#"+overall(pick)+" PICK\n\n"+club.getName().toUpperCase()+" seleciona\n\n"+choice.getName().toUpperCase()+"\n"+choice.getPrimaryPosition()+" • "+choice.getNationality()+" • "+choice.getAge()+" anos");TextButton confirm=ScreenUI.createPrimaryButton(game.skin,"CONFIRMAR");confirm.addListener(new ClickListener(){@Override public void clicked(InputEvent e,float x,float y){game.league.recordDraftSelection(pick,choice);pauseAfterUserPick=true;dialog.hide();announcement(choice,pick);}});dialog.button(confirm);dialog.button("VOLTAR");dialog.show(stage);}
    private void announcement(Player choice,DraftPick pick){Dialog dialog=new Dialog("WFL DRAFT",game.skin);dialog.text("WITH THE "+overall(pick)+"TH PICK IN THE\n"+(game.league.getCurrentSeason()+1)+" WFL DRAFT\n\n"+club.getName().toUpperCase()+"\nSELECTS\n\n"+choice.getName().toUpperCase()+"\n"+choice.getPrimaryPosition()+" • "+choice.getNationality()+" • "+choice.getAge()+"\n\nBig Board: #"+bigBoardRank(choice)+" • "+selectionValue(pick,choice));TextButton continueButton=ScreenUI.createPrimaryButton(game.skin,"CONTINUAR");continueButton.addListener(new ClickListener(){@Override public void clicked(InputEvent e,float x,float y){dialog.hide();refresh();}});dialog.button(continueButton);dialog.show(stage);}
    private int draftScore(Club drafting,Player p){return p.getOverall()*3+p.getPotential()+positionNeed(drafting,p.getPrimaryPosition())*5+(int)(Math.random()*8);}
    private int bigBoardRank(Player player){List<Player> board=new ArrayList<>(game.draftClass);board.sort(Comparator.comparingInt((Player p)->p.getOverall()+p.getPotential()/3).reversed());return board.indexOf(player)+1;}
    private String selectionValue(DraftPick pick,Player player){int delta=bigBoardRank(player)-overall(pick);return delta<=-4?"STEAL":delta>=5?"REACH":"VALOR JUSTO";}
    private Player recommended(){List<Player> pool=available();if(pool.isEmpty())return selected;pool.sort(Comparator.comparingInt((Player p)->draftScore(club,p)).reversed());return pool.get(0);}
    private int recommendationStars(Player p){return Math.max(1,Math.min(5,(p.getPotential()+positionNeed(club,p.getPrimaryPosition())*4-70)/6));}
    private String recommendationText(Player p){return positionNeed(club,p.getPrimaryPosition())>=4?"Melhor opção disponível e atende uma das maiores necessidades do elenco.":"Alto talento disponível, mas não é uma necessidade imediata.";}
    private int positionNeed(Club team,Position position){int count=0;for(Player p:team.getSquad())if(sameGroup(position,p.getPrimaryPosition()))count++;return Math.max(1,Math.min(5,5-count));}
    private boolean sameGroup(Position a,Position b){String x=a.name(),y=b.name();if("GK".equals(x))return "GK".equals(y);if(x.endsWith("B"))return y.endsWith("B");if(x.contains("M"))return y.contains("M");return y.equals("ST")||y.equals("CF")||y.equals("LW")||y.equals("RW");}
    private String projection(Player p){return p.getPotential()>=88?"Top 5":"Titular futuro";}private String needs(){return "GK "+stars(positionNeed(club,Position.GK))+"  CB "+stars(positionNeed(club,Position.CB))+"  LB "+stars(positionNeed(club,Position.LB))+"  CM "+stars(positionNeed(club,Position.CM))+"  RW "+stars(positionNeed(club,Position.RW))+"  ST "+stars(positionNeed(club,Position.ST));}private String stars(int n){String s="";for(int i=0;i<5;i++)s+=i<n?"★":"☆";return s;}
    @Override public void render(float d){Gdx.gl.glClearColor(0,0,0,1);Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);stage.act(d);stage.draw();}@Override public void resize(int w,int h){stage.getViewport().update(w,h,true);}@Override public void pause(){}@Override public void resume(){}@Override public void hide(){}@Override public void dispose(){stage.dispose();}
}
