package io.github.some_example_name.screens;

import com.badlogic.gdx.Gdx; import com.badlogic.gdx.Screen; import com.badlogic.gdx.graphics.GL20; import com.badlogic.gdx.scenes.scene2d.InputEvent; import com.badlogic.gdx.scenes.scene2d.Stage; import com.badlogic.gdx.scenes.scene2d.ui.*; import com.badlogic.gdx.scenes.scene2d.utils.ClickListener; import com.badlogic.gdx.utils.Align;
import io.github.some_example_name.Main; import io.github.some_example_name.model.Club; import io.github.some_example_name.utils.ResponsiveViewport; import io.github.some_example_name.utils.ScreenUI; import io.github.some_example_name.utils.StyleFactory;

/** Sorteio da cidade-sede da final da próxima WFL. */
public class FinalHostDrawScreen implements Screen {
    private final Main game; private final Club club; private final Stage stage;
    public FinalHostDrawScreen(Main game,Club club){this.game=game;this.club=club;this.stage=new Stage(new ResponsiveViewport());}
    @Override public void show(){Gdx.input.setInputProcessor(stage);refresh();}
    private void refresh(){stage.clear();Stack root=new Stack();root.setFillParent(true);stage.addActor(root);root.add(new Image(game.background));Table page=ScreenUI.createPage(true);page.add(ScreenUI.createHeader(game.skin,"WFL CHAMPIONSHIP "+(game.league.getCurrentSeason()+1),"SORTEIO DA SEDE")).growX().height(ScreenUI.HEADER_HEIGHT).padBottom(12f).row();Table panel=ScreenUI.createPanel();panel.top();String city=game.league.getFinalHostCity();if(city==null){panel.add(ScreenUI.createSectionTitle(game.skin,"CIDADES CANDIDATAS")).center().padTop(25f).row();panel.add(ScreenUI.createSubtitle(game.skin,"New York • London • Rio de Janeiro • München • Paris • Tokyo • Milano")).center().padTop(22f);}else{panel.add(ScreenUI.createSectionTitle(game.skin,"FINAL DA WFL SERÁ EM")).center().padTop(38f).row();panel.add(ScreenUI.createBoldValue(game.skin,city.toUpperCase(),StyleFactory.SOFT_YELLOW,Align.center)).center().padTop(24f).row();panel.add(ScreenUI.createSubtitle(game.skin,"Estádio: WFL Arena • Capacidade: 82.000")).center().padTop(12f);}page.add(panel).grow().padBottom(12f).row();TextButton action=ScreenUI.createPrimaryButton(game.skin,city==null?"SORTEAR SEDE":"CONTINUAR");action.addListener(new ClickListener(){@Override public void clicked(InputEvent e,float x,float y){if(game.league.getFinalHostCity()==null){game.league.drawFinalHostCity();refresh();}else game.setScreen(new OffSeasonScreen(game,club));}});page.add(action).width(280f).height(50f).center();root.add(page);}
    @Override public void render(float d){Gdx.gl.glClearColor(0,0,0,1);Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);stage.act(d);stage.draw();}@Override public void resize(int w,int h){stage.getViewport().update(w,h,true);}@Override public void pause(){}@Override public void resume(){}@Override public void hide(){}@Override public void dispose(){stage.dispose();}
}
